### ISSUE TITLE
crash when accessing window "Attributes..." on some windows

### ISSUE THREAD

**Issue by rakslice** [rakslice/wmaker#1]
When I do "Attributes..." on the window of keepass2, wmaker restarts with signal 11.

Running `.libs/wmaker --for-real` of a build with `--enable-debug` under `gdb`, I can get the stack trace:

```
Program received signal SIGSEGV, Segmentation fault.
create_tab_app_specific (frame_width=260, panel=0x5555558757e0, wwin=0x555555a22a30) at winspector.c:1447
1447                            is_userdef = get_attr_flag(&wapp->main_window_desc->defined_user_flags, &application_at
tr[i].flag);
(gdb) bt
#0  create_tab_app_specific (frame_width=260, panel=0x5555558757e0, wwin=0x555555a22a30) at winspector.c:1447
#1  createInspectorForWindow (wwin=wwin@entry=0x555555a22a30, xpos=xpos@entry=16777215, ypos=ypos@entry=16777215,
    showSelectPanel=showSelectPanel@entry=0) at winspector.c:1186
#2  0x00005555555ba224 in wShowInspectorForWindow (wwin=0x555555a22a30) at winspector.c:1270
#3  0x000055555559627f in menuMouseDown (desc=0x555555a54af8, event=<optimized out>) at menu.c:2003
#4  0x00005555555b0a60 in titlebarMouseDown (sender=<optimized out>, data=0x555555a22a30, event=0x7fffffffd500)
    at window.c:3035
#5  0x000055555558b003 in handleButtonPress (event=0x7fffffffd500) at event.c:876
#6  DispatchEvent (event=0x7fffffffd500) at event.c:233
#7  0x00007ffff7b9ade9 in WMHandleEvent (event=event@entry=0x7fffffffd500) at wevent.c:208
#8  0x000055555558ce67 in EventLoop () at event.c:400
#9  0x000055555556a0de in real_main (argv=<optimized out>, argc=2) at main.c:807
#10 main (argc=<optimized out>, argv=<optimized out>) at main.c:601
(gdb)
```

**Comment by rakslice** [comment]
```
(gdb) p wapp                                                                                                           |
$1 = (WApplication *) 0x0
```
